development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: clubhouse_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Fly.configuration.regional_redis_url || "redis://localhost:6379/1" %>
  password: <%= ENV.fetch("REDIS_PASSWORD", "redis") %>
  channel_prefix: clubhouse_production
