default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('CLUBHOUSE_DB_USERNAME', 'clubhouse') %>
  password: <%= ENV['CLUBHOUSE_DB_PASSWORD'] %>

development:
  <<: *default
  database: clubhouse_development

test:
  <<: *default
  database: clubhouse_test

production:
  <<: *default
  database: clubhouse_production
