default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("CLUBHOUSE_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("CLUBHOUSE_DB_PORT", 5432) %>
  username: <%= ENV.fetch("CLUBHOUSE_DB_USER", "clubhouse") %>
  password: <%= ENV.fetch("CLUBHOUSE_DB_PASSWORD", "clubhouse") %>
  timeout: 5000

development:
  <<: *default
  database: clubhouse_development

test:
  <<: *default
  database: clubhouse_test

production:
  <<: *default
  database: clubhouse_production
